sudo: false
language: ruby
# without --debug, JRuby doesn't support coverage reporting
before_install:
  - gem install bundler
env:
  - JRUBY_OPTS="--debug"
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.0-preview1
#  - jruby-head # linguist gem doesn't support JRuby; bundle install doesn't work.
  - ruby-head
