version: 2
jobs:
  build:
    working_directory: ~/quality
    docker:
      - image: apiology/circleci-ruby:latest
    steps:
      - checkout
      - type: cache-restore
        key: quality-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle --jobs=4
      - run: bundle exec rake clear_metrics
      - run: bundle exec rake --jobs=4 test quality
      - type: cache-save
        key: quality-{{ checksum "Gemfile.lock" }}
        paths:
          - "vendor/bundle"
